import { IPrizeConfig, IPersonConfig } from '@/types/storeType';
export const defaultPersonList = <IPersonConfig[]>
    [
        {
            id: 1,
            uid: "100001",
            name: "李尔涛",
            identity: "",
            "department": "董事会",
            isWin: false,
            x: 1,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 2,
            uid: "100002",
            name: "焦魁",
            identity: "",
            "department": "董事会",
            isWin: false,
            x: 2,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 3,
            uid: "100006",
            name: "张磊",
            identity: "",
            "department": "IT部",
            isWin: false,
            x: 3,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 4,
            uid: "100016",
            name: "田慧敏",
            identity: "",
            "department": "总部",
            isWin: false,
            x: 4,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 5,
            uid: "100020",
            name: "薛红晨",
            identity: "",
            "department": "董事会",
            isWin: false,
            x: 5,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 6,
            uid: "100028",
            name: "李辉",
            identity: "",
            "department": "青海分公司",
            isWin: false,
            x: 6,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 7,
            uid: "100037",
            name: "吴继红",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 7,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 8,
            uid: "100055",
            name: "祁开化",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 8,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 9,
            uid: "100060",
            name: "柏梅",
            identity: "",
            "department": "徐州嘉泰商贸有限公司",
            isWin: false,
            x: 9,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 10,
            uid: "100069",
            name: "秦洁",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 10,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 11,
            uid: "100079",
            name: "孙其会",
            identity: "",
            "department": "资源部",
            isWin: false,
            x: 11,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 12,
            uid: "100080",
            name: "李晓明",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 12,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 13,
            uid: "100082",
            name: "董丽君",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 13,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 14,
            uid: "100126",
            name: "王效敏",
            identity: "",
            "department": "人行部",
            isWin: false,
            x: 14,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 15,
            uid: "100177",
            name: "马来运",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 15,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 16,
            uid: "100185",
            name: "王兆蓬",
            identity: "",
            "department": "青岛分公司",
            isWin: false,
            x: 16,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 17,
            uid: "100186",
            name: "仇伟",
            identity: "",
            "department": "青岛吉泰港通供应链管理有限公司",
            isWin: false,
            x: 17,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 18,
            uid: "100190",
            name: "周亚公",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 18,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 19,
            uid: "100191",
            name: "王德伟",
            identity: "",
            "department": "人行部",
            isWin: false,
            x: 19,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 20,
            uid: "100194",
            name: "仇伟力",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 20,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 21,
            uid: "100196",
            name: "于利",
            identity: "",
            "department": "董事会",
            isWin: false,
            x: 21,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 22,
            uid: "100201",
            name: "顾友良",
            identity: "",
            "department": "青岛顺源吉",
            isWin: false,
            x: 22,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 23,
            uid: "100223",
            name: "严洪波",
            identity: "",
            "department": "临沂班列项目",
            isWin: false,
            x: 23,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 24,
            uid: "100266",
            name: "杨庆",
            identity: "",
            "department": "董事会",
            isWin: false,
            x: 24,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 25,
            uid: "100320",
            name: "仇梅",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 25,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 26,
            uid: "100324",
            name: "焦中海",
            identity: "",
            "department": "临沂班列项目",
            isWin: false,
            x: 26,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 27,
            uid: "100335",
            name: "胡兴军",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 27,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 28,
            uid: "100348",
            name: "傅春兰",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 28,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 29,
            uid: "100351",
            name: "霍成志",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 29,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 30,
            uid: "100356",
            name: "邹宗田",
            identity: "",
            "department": "资源部",
            isWin: false,
            x: 30,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 31,
            uid: "100357",
            name: "何旭龙",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 31,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 32,
            uid: "100369",
            name: "张云萍",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 32,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 33,
            uid: "100371",
            name: "刘洋",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 33,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 34,
            uid: "100375",
            name: "沈轩",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 34,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 35,
            uid: "100387",
            name: "马鑫",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 35,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 36,
            uid: "100395",
            name: "徐广磊",
            identity: "",
            "department": "总部",
            isWin: false,
            x: 36,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 37,
            uid: "100398",
            name: "董聪",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 37,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 38,
            uid: "100420",
            name: "崔德芝",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 38,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 39,
            uid: "100422",
            name: "田龙贵",
            identity: "",
            "department": "哈密陆港物流基地有限公司",
            isWin: false,
            x: 39,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 40,
            uid: "100423",
            name: "王浩",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 40,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 41,
            uid: "100426",
            name: "葛安杰",
            identity: "",
            "department": "兖州分公司-日照办",
            isWin: false,
            x: 41,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 42,
            uid: "100428",
            name: "杜鉴恒",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 42,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 43,
            uid: "100429",
            name: "矫立鑫",
            identity: "",
            "department": "青岛吉泰港通供应链管理有限公司",
            isWin: false,
            x: 43,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 44,
            uid: "100430",
            name: "孙绘杰",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 44,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 45,
            uid: "100434",
            name: "王文全",
            identity: "",
            "department": "兖州分公司-日照办",
            isWin: false,
            x: 45,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 46,
            uid: "100435",
            name: "高鲁",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 46,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 47,
            uid: "100441",
            name: "李丹",
            identity: "",
            "department": "人行部",
            isWin: false,
            x: 47,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 48,
            uid: "100447",
            name: "李秋江",
            identity: "",
            "department": "潍坊分公司",
            isWin: false,
            x: 48,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 49,
            uid: "100460",
            name: "李东",
            identity: "",
            "department": "总部",
            isWin: false,
            x: 49,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 50,
            uid: "100471",
            name: "吴学菊",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 50,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 51,
            uid: "100477",
            name: "陈军",
            identity: "",
            "department": "哈密陆港物流基地有限公司",
            isWin: false,
            x: 51,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 52,
            uid: "100486",
            name: "栗甜",
            identity: "",
            "department": "兖州分公司(本部)",
            isWin: false,
            x: 52,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 53,
            uid: "100487",
            name: "高亚洲",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 53,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 54,
            uid: "100502",
            name: "张超",
            identity: "",
            "department": "兖州分公司-日照办",
            isWin: false,
            x: 54,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 55,
            uid: "100506",
            name: "陈成亮",
            identity: "",
            "department": "临沂煅烧炭项目",
            isWin: false,
            x: 55,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 56,
            uid: "100507",
            name: "尉廷明",
            identity: "",
            "department": "临沂煅烧炭项目",
            isWin: false,
            x: 56,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 57,
            uid: "100517",
            name: "张丽娟",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 57,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 58,
            uid: "100519",
            name: "庞玉敏",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 58,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 59,
            uid: "100521",
            name: "\t 孙屹伟",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 59,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 60,
            uid: "100546",
            name: "赵春芳",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 60,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 61,
            uid: "100560",
            name: "王睿",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 61,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 62,
            uid: "100565",
            name: "高银屏",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 62,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 63,
            uid: "100569",
            name: "于伟",
            identity: "",
            "department": "广州分",
            isWin: false,
            x: 63,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 64,
            uid: "100572",
            name: "窦恺",
            identity: "",
            "department": "IT部",
            isWin: false,
            x: 64,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 65,
            uid: "100578",
            name: "岳海燕",
            identity: "",
            "department": "营销部",
            isWin: false,
            x: 65,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 66,
            uid: "100585",
            name: "成锦洪",
            identity: "",
            "department": "广州分",
            isWin: false,
            x: 66,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 67,
            uid: "100590",
            name: "成佳星",
            identity: "",
            "department": "人行部",
            isWin: false,
            x: 67,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 68,
            uid: "100594",
            name: "张玉臣",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 68,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 69,
            uid: "100596",
            name: "张瑞",
            identity: "",
            "department": "兖州分公司(本部)",
            isWin: false,
            x: 69,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 70,
            uid: "100598",
            name: "宋子涵",
            identity: "",
            "department": "兖州分公司(本部)",
            isWin: false,
            x: 70,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 71,
            uid: "100600",
            name: "黄笑珊",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 71,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 72,
            uid: "100610",
            name: "李海韬",
            identity: "",
            "department": "总部",
            isWin: false,
            x: 72,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 73,
            uid: "100622",
            name: "李长青",
            identity: "",
            "department": "人行部",
            isWin: false,
            x: 73,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 74,
            uid: "100638",
            name: "苏欢",
            identity: "",
            "department": "双汇项目",
            isWin: false,
            x: 74,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 75,
            uid: "100641",
            name: "苗新君",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 75,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 76,
            uid: "100642",
            name: "韩喜云",
            identity: "",
            "department": "兖州分公司-日照办",
            isWin: false,
            x: 76,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 77,
            uid: "100651",
            name: "刘春晓",
            identity: "",
            "department": "临沂班列项目",
            isWin: false,
            x: 77,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 78,
            uid: "100653",
            name: "杨红",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 78,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 79,
            uid: "100657",
            name: "潘文",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 79,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 80,
            uid: "100665",
            name: "宋强",
            identity: "",
            "department": "兖州分公司(本部)",
            isWin: false,
            x: 80,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 81,
            uid: "100771",
            name: "潘晓峰",
            identity: "",
            "department": "哈密陆港物流基地有限公司",
            isWin: false,
            x: 81,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 82,
            uid: "100779",
            name: "李永杰",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 82,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 83,
            uid: "100804",
            name: "倪莉",
            identity: "",
            "department": "人行部",
            isWin: false,
            x: 83,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 84,
            uid: "100805",
            name: "刘轩",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 84,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 85,
            uid: "100806",
            name: "陈钰莹",
            identity: "",
            department: "",
            isWin: false,
            x: 85,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 86,
            uid: "100808",
            name: "高红艳",
            identity: "",
            "department": "人行部",
            isWin: false,
            x: 86,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 87,
            uid: "100812",
            name: "王贺",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 87,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 88,
            uid: "100815",
            name: "王鸿羽",
            identity: "",
            "department": "哈密陆港物流基地有限公司",
            isWin: false,
            x: 88,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 89,
            uid: "100816",
            name: "肖璐",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 89,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 90,
            uid: "100817",
            name: "郑淋",
            identity: "",
            "department": "氧化铝项目",
            isWin: false,
            x: 90,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 91,
            uid: "100819",
            name: "阮梓聪",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 91,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 92,
            uid: "100820",
            name: "金苏苏",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 92,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 93,
            uid: "100821",
            name: "杨成乐",
            identity: "",
            "department": "人行部",
            isWin: false,
            x: 93,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 94,
            uid: "100822",
            name: "马娜",
            identity: "",
            "department": "氧化铝项目",
            isWin: false,
            x: 94,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 95,
            uid: "100823",
            name: "刘男",
            identity: "",
            "department": "项目部",
            isWin: false,
            x: 95,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 96,
            uid: "100824",
            name: "摆宁昱",
            identity: "",
            "department": "氧化铝项目",
            isWin: false,
            x: 96,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 97,
            uid: "100827",
            name: "李冷",
            identity: "",
            "department": "哈密陆港物流基地有限公司",
            isWin: false,
            x: 97,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 98,
            uid: "100829",
            name: "张海鹏",
            identity: "",
            "department": "吉泰物流(西安)有限公司",
            isWin: false,
            x: 98,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 99,
            uid: "100833",
            name: "沈海卓",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 99,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 100,
            uid: "100835",
            name: "陈鸿月",
            identity: "",
            "department": "氧化铝项目",
            isWin: false,
            x: 100,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 101,
            uid: "100836",
            name: "田浩",
            identity: "",
            department: "",
            isWin: false,
            x: 101,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 102,
            uid: "100837",
            name: "崔凤菊",
            identity: "",
            "department": "董事会",
            isWin: false,
            x: 102,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 103,
            uid: "100838",
            name: "杨清",
            identity: "",
            "department": "IT部",
            isWin: false,
            x: 103,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 104,
            uid: "100839",
            name: "张婷",
            identity: "",
            "department": "资源部",
            isWin: false,
            x: 104,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 105,
            uid: "100840",
            name: "王玮",
            identity: "",
            "department": "资源部",
            isWin: false,
            x: 105,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 106,
            uid: "100842",
            name: "张强",
            identity: "",
            "department": "哈密陆港物流基地有限公司",
            isWin: false,
            x: 106,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 107,
            uid: "100843",
            name: "王雪梅",
            identity: "",
            "department": "哈密陆港物流基地有限公司",
            isWin: false,
            x: 107,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 108,
            uid: "100844",
            name: "范徐海潮",
            identity: "",
            "department": "哈密陆港物流基地有限公司",
            isWin: false,
            x: 108,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 109,
            uid: "100846",
            name: "杨浩",
            identity: "",
            "department": "哈密陆港物流基地有限公司",
            isWin: false,
            x: 109,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 110,
            uid: "100847",
            name: "张双喜",
            identity: "",
            "department": "哈密陆港物流基地有限公司",
            isWin: false,
            x: 110,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 111,
            uid: "100849",
            name: "马超",
            identity: "",
            "department": "哈密陆港物流基地有限公司",
            isWin: false,
            x: 111,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 112,
            uid: "100852",
            name: "韩妍",
            identity: "",
            "department": "玉门东专用线",
            isWin: false,
            x: 112,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 113,
            uid: "100853",
            name: "朱效硕",
            identity: "",
            "department": "玉门东专用线",
            isWin: false,
            x: 113,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 114,
            uid: "100855",
            name: "毕宏伟",
            identity: "",
            "department": "玉门东专用线",
            isWin: false,
            x: 114,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 115,
            uid: "100859",
            name: "朱从亮",
            identity: "",
            "department": "营销部",
            isWin: false,
            x: 115,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 116,
            uid: "100862",
            name: "黄思欣",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 116,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 117,
            uid: "100863",
            name: "马伟奇",
            identity: "",
            "department": "氧化铝项目",
            isWin: false,
            x: 117,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 118,
            uid: "100864",
            name: "杨怀安",
            identity: "",
            "department": "氧化铝项目",
            isWin: false,
            x: 118,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 119,
            uid: "100865",
            name: "李晓朋",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 119,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 120,
            uid: "100866",
            name: "孔祥童",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 120,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 121,
            uid: "100867",
            name: "李汝贺",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 121,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 122,
            uid: "100868",
            name: "宋剑",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 122,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 123,
            uid: "100869",
            name: "商荣信",
            identity: "",
            "department": "兖州分公司(本部)",
            isWin: false,
            x: 123,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 124,
            uid: "100870",
            name: "赵以蒙",
            identity: "",
            "department": "兖州分公司-日照办",
            isWin: false,
            x: 124,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 125,
            uid: "100871",
            name: "杨少斌",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 125,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 126,
            uid: "100873",
            name: "刘继伟",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 126,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 127,
            uid: "100874",
            name: "范海波",
            identity: "",
            "department": "资源部",
            isWin: false,
            x: 127,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 128,
            uid: "100875",
            name: "潘付泉",
            identity: "",
            "department": "临沂班列项目",
            isWin: false,
            x: 128,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 129,
            uid: "100876",
            name: "徐吉祥",
            identity: "",
            "department": "临沂班列项目",
            isWin: false,
            x: 129,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 130,
            uid: "100879",
            name: "江鸿汝",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 130,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 131,
            uid: "100880",
            name: "王剑芳",
            identity: "",
            department: "",
            isWin: false,
            x: 131,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 132,
            uid: "100881",
            name: "谢文进",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 132,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 133,
            uid: "100883",
            name: "程全心",
            identity: "",
            "department": "营销部",
            isWin: false,
            x: 133,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 134,
            uid: "100885",
            name: "刘岩",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 134,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 135,
            uid: "100889",
            name: "王贤富",
            identity: "",
            department: "",
            isWin: false,
            x: 135,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 136,
            uid: "100890",
            name: "郭海斌",
            identity: "",
            "department": "财务部",
            isWin: false,
            x: 136,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 137,
            uid: "100891",
            name: "刘方方",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 137,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 138,
            uid: "100892",
            name: "韩天平",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 138,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 139,
            uid: "100893",
            name: "张才占",
            identity: "",
            "department": "玉门东专用线",
            isWin: false,
            x: 139,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 140,
            uid: "100894",
            name: "颜鲁玉",
            identity: "",
            "department": "玉门东专用线",
            isWin: false,
            x: 140,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 141,
            uid: "100895",
            name: "王爱涛",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 141,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 142,
            uid: "100896",
            name: "胡进荣",
            identity: "",
            "department": "人行部",
            isWin: false,
            x: 142,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 143,
            uid: "100897",
            name: "刘长瑞",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 143,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 144,
            uid: "100899",
            name: "管君",
            identity: "",
            "department": "兖州分公司-日照办",
            isWin: false,
            x: 144,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 145,
            uid: "100900",
            name: "霍丙帅",
            identity: "",
            "department": "兖州分公司(本部)",
            isWin: false,
            x: 145,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 146,
            uid: "100901",
            name: "陈健",
            identity: "",
            department: "",
            isWin: false,
            x: 146,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 147,
            uid: "100902",
            name: "赵延会",
            identity: "",
            "department": "兖州分公司-日照办",
            isWin: false,
            x: 147,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 148,
            uid: "100905",
            name: "梁皓天",
            identity: "",
            "department": "哈密陆港物流基地有限公司",
            isWin: false,
            x: 148,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 149,
            uid: "100906",
            name: "张成国",
            identity: "",
            "department": "玉门东专用线",
            isWin: false,
            x: 149,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 150,
            uid: "100907",
            name: "张花蕾",
            identity: "",
            "department": "哈密陆港物流基地有限公司",
            isWin: false,
            x: 150,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 151,
            uid: "100908",
            name: "覃煜彬",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 151,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 152,
            uid: "100909",
            name: "娄元国",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 152,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 153,
            uid: "100910",
            name: "马加峰",
            identity: "",
            department: "",
            isWin: false,
            x: 153,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 154,
            uid: "100911",
            name: "郑安东",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 154,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 155,
            uid: "100912",
            name: "邵锡贵",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 155,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 156,
            uid: "100913",
            name: "邵光军",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 156,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 157,
            uid: "100914",
            name: "韩其荣",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 157,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 158,
            uid: "100915",
            name: "邵光民",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 158,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 159,
            uid: "100916",
            name: "王凯生",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 159,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 160,
            uid: "100917",
            name: "李长民",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 160,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 161,
            uid: "100918",
            name: "邱国辉",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 161,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 162,
            uid: "100919",
            name: "李超",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 162,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 163,
            uid: "100920",
            name: "沈杰",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 163,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 164,
            uid: "100921",
            name: "蒋月",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 164,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 165,
            uid: "100922",
            name: "刘军营",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 165,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 166,
            uid: "100923",
            name: "牛曙光",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 166,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 167,
            uid: "100924",
            name: "商自军",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 167,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 168,
            uid: "100925",
            name: "董露兵",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 168,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 169,
            uid: "100926",
            name: "董海涛",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 169,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 170,
            uid: "100927",
            name: "张小涛",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 170,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 171,
            uid: "100928",
            name: "张红成",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 171,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 172,
            uid: "100929",
            name: "李阳文",
            identity: "",
            department: "",
            isWin: false,
            x: 172,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 173,
            uid: "100930",
            name: "李永军",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 173,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 174,
            uid: "100932",
            name: "张帅",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 174,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 175,
            uid: "100934",
            name: "马加勤",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 175,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 176,
            uid: "100935",
            name: "赵正利",
            identity: "",
            "department": "营运部",
            isWin: false,
            x: 176,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 177,
            uid: "100938",
            name: "吴雯青",
            identity: "",
            department: "",
            isWin: false,
            x: 177,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 178,
            uid: "100939",
            name: "江晓博",
            identity: "",
            department: "",
            isWin: false,
            x: 178,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 179,
            uid: "100940",
            name: "于小梅",
            identity: "",
            "department": "玉门东专用线",
            isWin: false,
            x: 179,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 180,
            uid: "100945",
            name: "朱国栋",
            identity: "",
            department: "",
            isWin: false,
            x: 180,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 181,
            uid: "100946",
            name: "周海鹰",
            identity: "",
            department: "",
            isWin: false,
            x: 181,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 182,
            uid: "100948",
            name: "文新荣",
            identity: "",
            department: "",
            isWin: false,
            x: 182,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 183,
            uid: "100949",
            name: "翟晓晶",
            identity: "",
            department: "",
            isWin: false,
            x: 183,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 184,
            uid: "100950",
            name: "李铁柱",
            identity: "",
            "department": "IT部",
            isWin: false,
            x: 184,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 185,
            uid: "100951",
            name: "张长再",
            identity: "",
            "department": "煤炭事业部",
            isWin: false,
            x: 185,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 186,
            uid: "100953",
            name: "商世升",
            identity: "",
            "department": "氧化铝项目",
            isWin: false,
            x: 186,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 187,
            uid: "100954",
            name: "刘中秋",
            identity: "",
            department: "",
            isWin: false,
            x: 187,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 188,
            uid: "100955",
            name: "徐伟",
            identity: "",
            department: "",
            isWin: false,
            x: 188,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 189,
            uid: "100956",
            name: "李文军",
            identity: "",
            department: "",
            isWin: false,
            x: 189,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 190,
            uid: "100957",
            name: "李富春",
            identity: "",
            department: "",
            isWin: false,
            x: 190,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 191,
            uid: "100958",
            name: "腾镇珷",
            identity: "",
            department: "",
            isWin: false,
            x: 191,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 192,
            uid: "100959",
            name: "高长姜",
            identity: "",
            department: "",
            isWin: false,
            x: 192,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        },
        {
            id: 193,
            uid: "100960",
            name: "秦岩",
            identity: "",
            department: "",
            isWin: false,
            x: 193,
            y: 1,
            createTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            updateTime: "Tue Jan 09 2024 23:20:07 GMT+0800 (China Standard Time)",
            prizeName: [],
            prizeId: [],
            prizeTime: []
        }
    ]
export const defaultMusicList = [
    {
        id: 'Geoff Knorr - China (The Industrial Era).ogg' + new Date().getTime().toString(),
        name: 'Geoff Knorr - China (The Industrial Era).ogg',
        url: 'https://1kw20.fun/resource/audio/Geoff Knorr - China (The Industrial Era).ogg'
    },
    {
        id: 'Geoff Knorr&Phill Boucher - China (The Atomic Era).ogg' + new Date().getTime().toString(),
        name: 'Geoff Knorr&Phill Boucher - China (The Atomic Era).ogg',
        url: 'https://1kw20.fun/resource/audio/Geoff Knorr&Phill Boucher - China (The Atomic Era).ogg'
    },
    {
        id: 'Radetzky March.mp3' + new Date().getTime().toString(),
        name: 'Radetzky March.mp3',
        url: 'https://1kw20.fun/resource/audio/Radetzky March.mp3'
    },
    {
        id: 'Shanghai.mp3' + new Date().getTime().toString(),
        name: 'Shanghai.mp3',
        url: 'https://1kw20.fun/resource/audio/Shanghai.mp3'
    },
    {
        id: 'Waltz No.2.mp3' + new Date().getTime().toString(),
        name: 'Waltz No.2.mp3',
        url: 'https://1kw20.fun/resource/audio/Waltz No.2.mp3'
    },
    {
        id: 'WildChinaTheme.mp3' + new Date().getTime().toString(),
        name: 'WildChinaTheme.mp3',
        url: 'https://1kw20.fun/resource/audio/WildChinaTheme.mp3'
    },
    {
        id: '边程&房东的猫 - 美好事物-再遇少年.ogg' + new Date().getTime().toString(),
        name: '边程&房东的猫 - 美好事物-再遇少年.ogg',
        url: 'https://1kw20.fun/resource/audio/边程&房东的猫 - 美好事物-再遇少年.ogg'
    },
    {
        id: '大乔小乔 - 相见难别亦难.ogg' + new Date().getTime().toString(),
        name: '大乔小乔 - 相见难别亦难.ogg',
        url: 'https://1kw20.fun/resource/audio/大乔小乔 - 相见难别亦难.ogg'
    },
    {
        id: '你要跳舞吗-新裤子.mp3' + new Date().getTime().toString(),
        name: '你要跳舞吗-新裤子.mp3',
        url: 'https://1kw20.fun/resource/audio/你要跳舞吗-新裤子.mp3'
    },
    {
        id: '生命-声音玩具.mp3' + new Date().getTime().toString(),
        name: '生命-声音玩具.mp3',
        url: 'https://1kw20.fun/resource/audio/生命-声音玩具.mp3'
    },
    {
        id: '与非门 - Happy New Year.ogg' + new Date().getTime().toString(),
        name: '与非门 - Happy New Year.ogg',
        url: 'https://1kw20.fun/resource/audio/与非门 - Happy New Year.ogg'
    },

]

export const defaultPrizeList = <IPrizeConfig[]>[
    {
        id: '001',
        name: '三等奖',
        sort: 1,
        isAll: false,
        count: 3,
        isUsedCount: 0,
        picture: {
            id: '2',
            name: '三等奖',
            url: 'https://1kw20.fun/resource/image/image3.png'
        },
        separateCount: {
            enable: true,
            countList: []
        },
        desc: '三等奖',
        isShow: true,
        isUsed: false,
        frequency: 1,
    },
    {
        id: '002',
        name: '二等奖',
        sort: 2,
        isAll: false,
        count: 2,
        isUsedCount: 0,
        picture: {
            id: '1',
            name: '二等奖',
            url: 'https://1kw20.fun/resource/image/image2.png'
        },
        separateCount: {
            enable: false,
            countList: []
        },
        desc: '二等奖',
        isShow: true,
        isUsed: false,
        frequency: 1,
    },
    {
        id: '003',
        name: '一等奖',
        sort: 3,
        isAll: false,
        count: 1,
        isUsedCount: 0,
        picture: {
            id: '0',
            name: '一等奖',
            url: 'https://1kw20.fun/resource/image/image1.png'
        },
        separateCount: {
            enable: false,
            countList: []
        },
        desc: '一等奖',
        isShow: true,
        isUsed: false,
        frequency: 1,
    },
    {
        id: '004',
        name: '超级大奖',
        sort: 4,
        isAll: false,
        count: 1,
        isUsedCount: 0,
        picture: {
            id: '3',
            name: '超级奖',
            url: 'https://1kw20.fun/resource/image/image4.png'
        },
        separateCount: {
            enable: false,
            countList: []
        },
        desc: '超级大奖',
        isShow: true,
        isUsed: false,
        frequency: 1,
    },
    {
        id: '005',
        name: '特别奖',
        sort: 5,
        isAll: false,
        count: 1,
        isUsedCount: 0,
        picture: {
            id: '4',
            name: '特别奖',
            url: 'https://1kw20.fun/resource/image/image5.png'
        },
        separateCount: {
            enable: false,
            countList: []
        },
        desc: '特别奖',
        isShow: true,
        isUsed: false,
        frequency: 1,
    }
]
export const defaultCurrentPrize = <IPrizeConfig>{
    id: '001',
    name: '三等奖',
    sort: 1,
    isAll: false,
    count: 12,
    isUsedCount: 0,
    picture: {
        id: '2',
        name: '三等奖',
        url: 'https://1kw20.fun/resource/image/image3.png'
    },
    separateCount: {
        enable: true,
        countList: []
    },
    desc: '三等奖',
    isShow: true,
    isUsed: false,
    frequency: 1,
}
export const defaultTemporaryPrize = <IPrizeConfig>{
    id: '',
    name: '',
    sort: 0,
    isAll: false,
    count: 1,
    isUsedCount: 0,
    picture: {
        id: '-1',
        name: '',
        url: ''
    },
    separateCount: {
        enable: true,
        countList: []
    },
    desc: '',
    isShow: false,
    isUsed: false,
    frequency: 1,
}

export const defaultImageList = [
    {
        id: '0',
        name: '一等奖',
        url: 'https://1kw20.fun/resource/image/image1.png'
    },
    {
        id: '1',
        name: '二等奖',
        url: 'https://1kw20.fun/resource/image/image2.png'
    },
    {
        id: '2',
        name: '三等奖',
        url: 'https://1kw20.fun/resource/image/image3.png'
    },
    {
        id: '3',
        name: '超级奖',
        url: 'https://1kw20.fun/resource/image/image4.png'
    },
    {
        id: '4',
        name: '特别奖',
        url: 'https://1kw20.fun/resource/image/image5.png'
    }
]
export const defaultPatternList = [21, 38, 55, 54, 53, 70, 87, 88, 89, 23, 40, 57, 74, 91, 92, 93, 76, 59, 42, 25, 24, 27, 28, 29, 46, 63, 62, 61, 78, 95, 96, 97, 20, 19, 31, 48, 65, 66, 67, 84, 101, 100, 99, 32, 33]
